### ISSUE TITLE
Menu X/Y Position

### ISSUE THREAD

**Issue by eyeshark** [trv6/Windower4#1]
I have been trying to adjust where the menu appears on the screen relative to the rhombus. I am a novice, but know enough to get by. I suspect the variable I need is in Rhombus.lua but I have tried adjusting many things with no success. I have provided an edited screenshot below to visualize what I'm trying to accomplish.

Thank you!

![image](https://user-images.githubusercontent.com/20376383/162787481-f8130617-2260-468e-9484-a1a9c226ddfe.png)

![image](https://user-images.githubusercontent.com/20376383/162787517-285b74b1-3dbf-4822-aae0-940bd4387f70.png)

**Comment by trv6** [comment]
Oh, that's pretty cool.
Unfortunately, the addon isn't very well written and moving the icon will take some effort on your part.
I haven't looked at this file in a long time, but it looks like all of the primitives are positioned relative to the variables `x_offset` and `y_offset`. The icon object is stored in the variable `menu_icon`. You'll need to adjust the position of the icon and change the collision detection in the mouse function.
For the position, line 53 moves the icon when the settings are updated and line 292 moves it while it is dragged. You'll need to play around with adding additional offsets to the x and y arguments until things look right.
For collision, you'll need to change lines 287, 354, and 422, which are all the same. I think you should be able to add the same offsets as above to the parenthesized terms.

**Comment by eyeshark** [comment]
Thanks for the reply! I had gotten as far as to get things moved, but the collision detection was a problem. I will try again today!

**Comment by eyeshark** [comment]
That worked like a charm! I was thinking it was backward, that I was moving the list around the rhombus instead of the other way around. I was banging my head around for hours playing with this. Really cool code! Thanks for the reply. I wasn't sure after so long that you would even see my comment but I figured it was worth a shot and am glad I asked!

My nice little bottom right corner, now with a fully functioning menu! :)
![image](https://user-images.githubusercontent.com/20376383/162966871-8af88982-bdef-4f80-b596-369fd52c9b3d.png)

**Comment by trv6** [comment]
Nicely done!
